[project]
name = "youtube-mcp-server"
version = "0.1.0"
description = "query youtube videos mcp server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ezmcp>=0.0.2",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
